<a href="https://colab.research.google.com/github/pankajkumaryadav-ai-ds/DWM-LAB/blob/main/DWM(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# a) Dealing with categorical data
import pandas as pd
import io
dataset=pd.read_excel("/content/Salary.xlsx")
X=dataset.iloc[:,[0]].values
Y=dataset.iloc[:,[3]].values
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder()
ohe_X=onehotencoder.fit_transform(X)
ohe_Y=onehotencoder.fit_transform(Y)
X=ohe_X.toarray()
Y=ohe_Y.toarray()
print(X)
print(Y)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [11]:
import numpy as np
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)
sc_y=StandardScaler()
Y_train=Y_train.values.reshape((len(Y_train),1))
Y_train=sc_y.fit_transform(Y_train)
Y_train =Y_train.ravel()
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[-0.77459667  1.         -0.37796447         nan         nan]
 [ 1.29099445 -1.         -0.37796447 -1.                 nan]
 [ 1.29099445 -1.         -0.37796447         nan         nan]
 [-0.77459667  1.         -0.37796447         nan         nan]
 [-0.77459667 -1.          2.64575131  1.          0.        ]
 [-0.77459667  1.         -0.37796447         nan         nan]
 [-0.77459667  1.         -0.37796447         nan         nan]
 [ 1.29099445 -1.         -0.37796447         nan         nan]]
[ 1. -1. -1.  1. -1.  1. -1.  1.]
[[-7.74596669e-01 -1.00000000e+00  2.64575131e+00             nan
  -8.69766667e+03]
 [-7.74596669e-01 -1.00000000e+00  2.64575131e+00             nan
              nan]]
4    1
8    0
Name: OnlineShopper, dtype: int64


In [16]:
np.shape(X_test)

(2, 5)

In [10]:
# c) Splitting dataset into Training and Testing Sets
import pandas as pd
from sklearn.model_selection import train_test_split
dataset=pd.read_csv('/content/Pre_Salary.csv')
print(dataset)
#output vector
y=dataset.OnlineShopper

#input vector
x=dataset.drop('OnlineShopper',axis=1)
#split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)
#verify
print("shape of original dataset:",dataset.shape)
print("shape of input-training set",X_train.shape)
print("shape of output-training set",Y_train.shape)
print("shape of input-testing set",X_test.shape)
print("shape of output-testing set",Y_test.shape)

   zero  one  two        Age       Salary  OnlineShopper
0     0    1    0        NaN          NaN              0
1     1    0    0        NaN          NaN              1
2     0    0    1  52.560000  85231.00000              0
3     1    0    0        NaN          NaN              0
4     0    0    1        NaN  76533.33333              1
5     0    1    0        NaN          NaN              1
6     1    0    0  43.777778          NaN              0
7     0    1    0        NaN          NaN              1
8     0    0    1        NaN          NaN              0
9     0    1    0        NaN          NaN              1
shape of original dataset: (10, 6)
shape of input-training set (8, 5)
shape of output-training set (8,)
shape of input-testing set (2, 5)
shape of output-testing set (2,)
