<a href="https://colab.research.google.com/github/pankajkumaryadav-ai-ds/DWM-LAB/blob/main/DWM(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# a) Create multi-dimensional arrays and find its shape and dimension
import numpy as np
#importing NumPy with alias np
a=np.array([[1,2,3],[2,3,4],[3,4,5]])#creation of multi-dimensional array with array() method
# shape
b=a.shape# b=np.shape(a), here shape is a method which returns number of dimensions and number of values each dimension is holding
print("shape:",b)#print("shape:",a.shape)
# dimension
c=a.ndim #ndim() is a method which returns the dimension of the given Array
print("dimensions:",a.ndim)


shape: (3, 3)
dimensions: 2


In [10]:
# b) Create a matrix full of zeros and ones 
#matrix full of zeros
#zeros() is a method which creates zeros with specified array shape
z=np.zeros((2,2))
print("zeros:",z)
#matrix full of ones
#ones() is a method which creates ones with specified array shape
o=np.ones((2,2))
print("ones:",o)

zeros: [[0. 0.]
 [0. 0.]]
ones: [[1. 1.]
 [1. 1.]]


In [12]:
# c) Reshape and flatten data in the array 
#matrix reshape
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
#get a new shape to an array without changing its data
b=a.reshape(4,2,2)
print("original:",a)
print("Reshape:",b)
#matrix flatten
#doesn’t change contents of an existing array. Instead, it returns a new flat array. 
c=a.flatten()
print("flatten:",c)

original: [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
Reshape: [[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]
flatten: [1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


In [14]:
# d) Append data vertically and horizontally 
#Appending data vertically
x=np.array([[10,20],[80,90]])
y=np.array([[30,40],[60,70]])
# Using the vstack() function, items of arrays are arranged vertically
v=np.vstack((x,y))
print("vertically:",v)
#Appending data horizontally
# Using the hstack() function, items of arrays are arranged horizontally
h=np.hstack((x,y))
print("horizontally:",h)

vertically: [[10 20]
 [80 90]
 [30 40]
 [60 70]]
horizontally: [[10 20 30 40]
 [80 90 60 70]]


In [15]:
# e) Apply indexing and slicing on array 
#indexing
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
temp=a[[0,1,2,3],[1,1,1,1]]
print("indexing",temp)
# slicing
i=a[:4,::2]
print("slicing",i)

indexing [2 3 4 5]
slicing [[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [18]:
# f) Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation
a=np.array([[1,3,-1,4],[3,-2,1,4]])
#min for finding minimum of an array
b=a.min()
print("minimum:",b)
#max for finding maximum of an array
c=a.max()
print("maximum:",c)
# mean
a=np.array([1,2,3,4,5])
d=a.mean()
print("mean:",d)
# median
e=np.median(a)
print("median:",e)
# standard Deviation
f=a.std()
print("Standard deviation is :",f)

minimum: -2
maximum: 4
mean: 3.0
median: 3.0
Standard deviation is : 1.4142135623730951
